name: unix port in cygwin

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'build rev'
        default: '1.0.0'
        required: true
        type: string

jobs:
  standard:
    runs-on: windows-latest
    steps:
    - name: Send greeting
      run: echo "version ${{ inputs.name }}"    
    - uses: actions/checkout@v4
    - name: Checkout Submodule micropython
      run: |
        git submodule init
        git submodule update --recursive -- micropython
        
    - name: Setup Cygwin
      uses: cygwin/cygwin-install-action@v4
      with:
        platform: x86_64
        packages: >  
          git 
          python39 
          wget
          tar
          make
          gcc-core
          gcc-g++
          autoconf
          automake
          bison
          pkgconf
          pkg-config
          libffi6
          libffi8
          libffi-devel
          libtool
          libpkgconf3
          libpkgconf4
          libSDL2_2.0_0
          libSDL2-devel
        
    - name: Build with Cygwin
      run: |
         bash.exe -eo pipefail -o igncr -c "source tools/ci.sh && ci_unix_build_cygwin"

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: mpy_efont_demo
        path: |
          micropython/ports/unix/build-standard/micropython.exe
          c:\cygwin64\bin\cyggcc_s-seh-1.dll
          c:\cygwin64\bin\cygstdc++-6.dll
          c:\cygwin64\bin\cygwin1.dll
          c:\cygwin64\bin\cygSDL2-2-0-0.dll
          examples/
