name: esp32 port

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'output folder'
        default: examples'
        required: true
        type: string

jobs:
  build_idf50:
    runs-on: ubuntu-20.04

    steps:
    - name: Send greeting
      run: echo "output ${{ inputs.name }}"
    - uses: actions/checkout@v4
    - name: Get mkfatfs
      run: |
        wget -O mkfatfs https://github.com/labplus-cn/mkfatfs/releases/download/v2.0.1/mkfatfs_linux_x86
        chmod +x mkfatfs
    - name: Make FS-Image
      run: ./mkfatfs -c ./${{inputs.name}} -t fatfs -s 4194304 efore_s3_vfs.bin
    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: mpy_efont_esp32s3_img
        path: |
          efore_s3_vfs.bin

      
